version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: optique
      POSTGRES_PASSWORD: optique
      POSTGRES_DB: optique
    ports:
      - 5432:5432

